apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavbuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mavbuggy
  template:
    metadata:
      labels:
        app: mavbuggy
    spec:
      containers:
      - name: mavbuggy
        image: 748554773005.dkr.ecr.us-west-2.amazonaws.com/mav
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mavbuggy
    k8s-app: mavbuggy
  name: mavbuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: mavbuggy
